#!/usr/bin/env python3
"""Build poetry HTML pages: an index page and one page per group, plus individual poem pages."""

import os
import re
import html

POETRY_DIR = "/Users/lukstafi/lukstafi.github.io/poetry"
OUTPUT_DIR = POETRY_DIR  # HTML files go alongside the .md files

GROUPS = {
    "body-in-motion": {
        "name": "The Body in Motion",
        "description": "Dance, movement, embodied sensation",
    },
    "hearts-coordinates": {
        "name": "The Heart's Coordinates",
        "description": "Love, longing, desire, interpersonal connection",
    },
    "self-assembled": {
        "name": "The Self, Assembled and Questioned",
        "description": "Identity, selfhood, vulnerability, resilience",
    },
    "mind-and-language": {
        "name": "Mind, Language, and the Poem Itself",
        "description": "Meta-poetry, self-reference, thought and expression",
    },
    "worlds-in-mind": {
        "name": "Bodies in Space, Worlds in Mind",
        "description": "Cosmic scale, stars, science fiction, the human inside the vast",
    },
    "landscape-and-creature": {
        "name": "Landscape, Season, Creature",
        "description": "Nature, weather, animals, sensory life",
    },
    "persons-and-portraits": {
        "name": "Persons and Portraits",
        "description": "Poems shaped around specific people",
    },
    "polski": {
        "name": "Polski / Polish",
        "description": "Polish and bilingual poems",
    },
    "voiced-by-machines": {
        "name": "Voiced by Machines",
        "description": "Poems generated by GPT-2 language models",
    },
    "collections": {
        "name": "Collections &amp; Marginalia",
        "description": "Compilations and meta-documents",
    },
}

# Ordered group IDs for display
GROUP_ORDER = [
    "body-in-motion",
    "hearts-coordinates",
    "self-assembled",
    "mind-and-language",
    "worlds-in-mind",
    "landscape-and-creature",
    "persons-and-portraits",
    "polski",
    "voiced-by-machines",
    "collections",
]

HEAD = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <title>{title}</title>
  <link rel="stylesheet" href="/assets/tufte.css">
  <link rel="stylesheet" href="/assets/site.css">
  <link rel="stylesheet" href="/assets/poetry.css">
  <script>(function(){{var t=localStorage.getItem('theme-preference');if(t)document.documentElement.setAttribute('data-theme',t);}})()</script>
</head>
<body>
<article>
<header>
  <nav class="site-nav">
    {nav}
  </nav>
  <h1 class="title">{heading}</h1>
  {subtitle}
</header>
"""

FOOT = """\
</article>
<div class="theme-toggle">
  <button id="theme-btn" aria-label="Toggle dark mode">&#9788;</button>
</div>
<script src="/assets/theme-toggle.js"></script>
</body>
</html>
"""


def parse_frontmatter(filepath):
    """Parse YAML-ish frontmatter from a markdown file."""
    meta = {}
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    if not content.startswith('---'):
        return meta, content
    end = content.index('---', 3)
    fm = content[3:end]
    body = content[end + 3:].strip()
    for line in fm.strip().split('\n'):
        if ':' in line:
            key, val = line.split(':', 1)
            raw_val = val.strip()
            # Check if value was quoted
            if raw_val.startswith('"') and raw_val.endswith('"'):
                val = raw_val[1:-1].replace('\\"', '"')
            # Parse list values like [English, GPT-2] only for known list fields
            elif raw_val.startswith('[') and raw_val.endswith(']'):
                val = [v.strip() for v in raw_val[1:-1].split(',') if v.strip()]
            else:
                val = raw_val
            meta[key.strip()] = val
    return meta, body


def clean_title(title):
    """Remove leading markers like ? # * [ ] from display title."""
    t = re.sub(r'^[?#*\s]+', '', title)
    t = re.sub(r'^\[', '', t)
    t = re.sub(r'\]$', '', t)
    return t.strip() or title


def markdown_to_html(md_text):
    """Very simple markdown-to-HTML for poetry content."""
    lines = md_text.split('\n')
    out = []
    in_blockquote = False
    bq_lines = []

    def flush_bq():
        nonlocal in_blockquote, bq_lines
        if bq_lines:
            inner = '<br>\n'.join(bq_lines)
            out.append(f'<blockquote>{inner}</blockquote>')
            bq_lines = []
        in_blockquote = False

    for line in lines:
        # Check for trailing two spaces (markdown line break) before stripping
        add_br = line.rstrip('\n').endswith('  ')
        display = line.rstrip()
        if add_br:
            display = display.rstrip()

        if display.startswith('> '):
            in_blockquote = True
            bq_content = display[2:]
            bq_content = inline_format(html.escape(bq_content))
            bq_lines.append(bq_content)
        else:
            if in_blockquote:
                flush_bq()
            if display == '':
                out.append('')
            else:
                escaped = html.escape(display)
                escaped = inline_format(escaped)
                if add_br:
                    out.append(escaped + '<br>')
                else:
                    out.append(escaped)

    if in_blockquote:
        flush_bq()

    # Join and wrap in a poem div
    result = '\n'.join(out)
    # Convert blank lines to paragraph breaks
    result = re.sub(r'\n\n+', '\n</p>\n<p>', result)
    result = f'<p>{result}</p>'
    # Clean up empty paragraphs
    result = result.replace('<p></p>', '')
    return result


def inline_format(text):
    """Apply inline markdown formatting: bold, italic, links."""
    # Bold **text**
    text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)
    # Italic *text* (but not ** or ***)
    text = re.sub(r'(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)', r'<em>\1</em>', text)
    # Links [text](url)
    text = re.sub(r'\[([^\]]+)\]\(([^)]+)\)', r'<a href="\2">\1</a>', text)
    return text


def build_poem_page(meta, body, slug):
    """Build an individual poem HTML page."""
    title = meta.get('title', 'Untitled')
    display_title = clean_title(title)
    date = meta.get('date', '')
    group_id = meta.get('group', '')
    group_name = GROUPS.get(group_id, {}).get('name', '')

    nav_parts = ['<a href="/">&larr; Home</a> &middot; <a href="/poetry/">Poetry</a>']
    if group_id and group_name:
        nav_parts.append(f' &middot; <a href="/poetry/{group_id}.html">{group_name}</a>')

    subtitle = f'<p class="subtitle">{date}</p>' if date else ''

    page = HEAD.format(
        title=html.escape(display_title) + ' &ndash; Poetry',
        nav=''.join(nav_parts),
        heading=html.escape(display_title),
        subtitle=subtitle,
    )

    page += '<section class="poem-content">\n'
    page += markdown_to_html(body)
    page += '\n</section>\n'
    page += FOOT

    outpath = os.path.join(OUTPUT_DIR, f'{slug}.html')
    with open(outpath, 'w', encoding='utf-8') as f:
        f.write(page)
    return outpath


def build_group_page(group_id, poems):
    """Build a group listing page."""
    group = GROUPS[group_id]
    name = group['name']
    desc = group['description']

    # Sort poems by date descending
    poems.sort(key=lambda p: p['date'], reverse=True)

    nav = '<a href="/">&larr; Home</a> &middot; <a href="/poetry/">Poetry</a>'
    subtitle = f'<p class="subtitle">{desc}</p>'

    page = HEAD.format(
        title=html.escape(name) + ' &ndash; Poetry',
        nav=nav,
        heading=name,
        subtitle=subtitle,
    )

    page += '<section>\n<ul class="poem-list">\n'
    for p in poems:
        display = clean_title(p['title'])
        page += f'  <li><a href="/poetry/{p["slug"]}.html">{html.escape(display)}</a>'
        page += f' <span class="poem-date">{p["date"]}</span></li>\n'
    page += '</ul>\n</section>\n'
    page += FOOT

    outpath = os.path.join(OUTPUT_DIR, f'{group_id}.html')
    with open(outpath, 'w', encoding='utf-8') as f:
        f.write(page)
    print(f"  Group page: {group_id}.html ({len(poems)} poems)")


def build_index_page(group_poems):
    """Build the main poetry index page."""
    nav = '<a href="/">&larr; Home</a>'
    subtitle = '<p class="subtitle">Lukasz Stafiniak</p>'

    page = HEAD.format(
        title='Poetry &ndash; Digits',
        nav=nav,
        heading='Digits',
        subtitle=subtitle,
    )

    page += '<section>\n'
    for gid in GROUP_ORDER:
        group = GROUPS[gid]
        poems = group_poems.get(gid, [])
        if not poems:
            continue
        page += f'<div class="poetry-group">\n'
        page += f'  <h2><a href="/poetry/{gid}.html">{group["name"]}</a></h2>\n'
        page += f'  <p class="group-description">{group["description"]}</p>\n'
        page += f'  <p class="group-count">{len(poems)} poems</p>\n'
        page += f'</div>\n'
    page += '</section>\n'
    page += FOOT

    outpath = os.path.join(OUTPUT_DIR, 'index.html')
    with open(outpath, 'w', encoding='utf-8') as f:
        f.write(page)
    print(f"  Index page: index.html")


def main():
    # Read all poems
    poems = []
    for fname in sorted(os.listdir(POETRY_DIR)):
        if not fname.endswith('.md'):
            continue
        slug = fname[:-3]
        filepath = os.path.join(POETRY_DIR, fname)
        meta, body = parse_frontmatter(filepath)
        meta['slug'] = slug
        poems.append((meta, body))

    print(f"Found {len(poems)} poems")

    # Build individual poem pages
    for meta, body in poems:
        build_poem_page(meta, body, meta['slug'])

    # Group poems
    group_poems = {}
    for meta, body in poems:
        gid = meta.get('group', '')
        if gid:
            group_poems.setdefault(gid, []).append({
                'title': meta.get('title', 'Untitled'),
                'date': meta.get('date', ''),
                'slug': meta['slug'],
            })

    # Build group pages
    for gid in GROUP_ORDER:
        if gid in group_poems:
            build_group_page(gid, group_poems[gid])

    # Build index page
    build_index_page(group_poems)

    total_html = len(poems) + len(group_poems) + 1
    print(f"\nGenerated {total_html} HTML files in {OUTPUT_DIR}/")


if __name__ == '__main__':
    main()
